// User Action
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// Movie Action
export const GET_MOVIES_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const CLEAR_CURRENT_MOVIE = "CLEAR_CURRENT_MOVIE";
export const MOVIE_NOT_FOUND = "MOVIE_NOT_FOUND";
export const MOVIE_LOADING = "MOVIE_LOADING";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
